namespace Edelstein.WvsLogin.Sockets
{
    public enum LoginRecvOperations
    {
        CheckPassword = 0x1,
        GuestIDLogin = 0x2,
        AccountInfoRequest = 0x3,
        WorldInfoRequest = 0x4,
        SelectWorld = 0x5,
        CheckUserLimit = 0x6,
        ConfirmEULA = 0x7,
        SetGender = 0x8,
        CheckPinCode = 0x9,
        UpdatePinCode = 0xA,
        WorldRequest = 0xB,
        LogoutWorld = 0xC,
        ViewAllChar = 0xD,
        SelectCharacterByVAC = 0xE,
        VACFlagSet = 0xF,
        CheckNameChangePossible = 0x10,
        RegisterNewCharacter = 0x11,
        CheckTransferWorldPossible = 0x12,
        SelectCharacter = 0x13,
        MigrateIn = 0x14,
        CheckDuplicatedID = 0x15,
        CreateNewCharacter = 0x16,
        CreateNewCharacterInCS = 0x17,
        DeleteCharacter = 0x18,
        AliveAck = 0x19,
        ExceptionLog = 0x1A,
        SecurityPacket = 0x1B,
        EnableSPWRequest = 0x1C,
        CheckSPWRequest = 0x1D,
        EnableSPWRequestByACV = 0x1E,
        CheckSPWRequestByACV = 0x1F,
        CheckOTPRequest = 0x20,
        CheckDeleteCharacterOTP = 0x21,
        CreateSecurityHandle = 0x22,
        SSOErrorLog = 0x23,
        ClientDumpLog = 0x24,
        CheckExtraCharInfo = 0x25,
        CreateNewCharacter_Ex = 0x26
    }
}