// <auto-generated />
using System;
using Edelstein.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Edelstein.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181120115959_AddQuickslotKeys")]
    partial class AddQuickslotKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Edelstein.Database.Entities.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .HasMaxLength(128);

                    b.Property<string>("SPW")
                        .HasMaxLength(128);

                    b.Property<int>("State");

                    b.Property<string>("Username")
                        .HasMaxLength(13);

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.AccountData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountID");

                    b.Property<int>("SlotCount");

                    b.Property<byte>("WorldID");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("AccountData");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("AP");

                    b.Property<short>("DEX");

                    b.Property<int?>("DataID");

                    b.Property<int>("EXP");

                    b.Property<int>("Face");

                    b.Property<int>("FieldID");

                    b.Property<byte>("FieldPortal");

                    b.Property<byte>("Gender");

                    b.Property<int>("HP");

                    b.Property<int>("Hair");

                    b.Property<short>("INT");

                    b.Property<short>("Job");

                    b.Property<short>("LUK");

                    b.Property<byte>("Level");

                    b.Property<int>("MP");

                    b.Property<int>("MaxHP");

                    b.Property<int>("MaxMP");

                    b.Property<int>("Money");

                    b.Property<string>("Name")
                        .HasMaxLength(13);

                    b.Property<short>("POP");

                    b.Property<int>("PlayTime");

                    b.Property<short>("SP");

                    b.Property<short>("STR");

                    b.Property<byte>("Skin");

                    b.Property<short>("SubJob");

                    b.Property<int>("TempEXP");

                    b.HasKey("ID");

                    b.HasIndex("DataID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.FunctionKey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<int?>("CharacterID");

                    b.Property<int>("Key");

                    b.Property<byte>("Type");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("FunctionKey");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemInventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CharacterID");

                    b.Property<byte>("SlotMax");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("ItemInventory");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateExpire");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ItemInventoryID");

                    b.Property<short>("Position");

                    b.Property<int>("TemplateID");

                    b.HasKey("ID");

                    b.HasIndex("ItemInventoryID");

                    b.ToTable("ItemSlot");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ItemSlot");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Macro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CharacterID");

                    b.Property<bool>("Mute");

                    b.Property<string>("Name");

                    b.Property<int>("Skill1");

                    b.Property<int>("Skill2");

                    b.Property<int>("Skill3");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Macro");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.QuickslotKey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CharacterID");

                    b.Property<int>("Key");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("QuickslotKey");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Shop.NPCShop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TemplateID");

                    b.HasKey("ID");

                    b.ToTable("NPCShops");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Shop.NPCShopItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("DiscountRate");

                    b.Property<int>("ItemPeriod");

                    b.Property<int>("LevelLimited");

                    b.Property<short>("MaxPerSlot");

                    b.Property<int?>("NPCShopID");

                    b.Property<int>("Position");

                    b.Property<int>("Price");

                    b.Property<short>("Quantity");

                    b.Property<int>("Stock");

                    b.Property<int>("TemplateID");

                    b.Property<int>("TokenPrice");

                    b.Property<int>("TokenTemplateID");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.HasIndex("NPCShopID");

                    b.ToTable("NPCShopItem");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.SkillRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CharacterID");

                    b.Property<DateTime?>("DateExpire");

                    b.Property<int>("Info");

                    b.Property<int>("MasterLevel");

                    b.Property<int>("Skill");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("SkillRecord");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlotBundle", b =>
                {
                    b.HasBaseType("Edelstein.Database.Entities.Inventory.ItemSlot");

                    b.Property<short>("Attribute");

                    b.Property<short>("MaxNumber");

                    b.Property<short>("Number");

                    b.Property<string>("Title")
                        .HasMaxLength(13);

                    b.ToTable("ItemSlotBundle");

                    b.HasDiscriminator().HasValue("ItemSlotBundle");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlotEquip", b =>
                {
                    b.HasBaseType("Edelstein.Database.Entities.Inventory.ItemSlot");

                    b.Property<short>("ACC");

                    b.Property<short>("Attribute")
                        .HasColumnName("ItemSlotEquip_Attribute");

                    b.Property<byte>("CHUC");

                    b.Property<byte>("CUC");

                    b.Property<short>("Craft");

                    b.Property<short>("DEX");

                    b.Property<int>("Durability");

                    b.Property<short>("EVA");

                    b.Property<int>("EXP");

                    b.Property<byte>("Grade");

                    b.Property<short>("INT");

                    b.Property<int>("IUC");

                    b.Property<short>("Jump");

                    b.Property<short>("LUK");

                    b.Property<byte>("Level");

                    b.Property<byte>("LevelUpType");

                    b.Property<short>("MAD");

                    b.Property<short>("MDD");

                    b.Property<short>("MaxHP");

                    b.Property<short>("MaxMP");

                    b.Property<short>("Option1");

                    b.Property<short>("Option2");

                    b.Property<short>("Option3");

                    b.Property<short>("PAD");

                    b.Property<short>("PDD");

                    b.Property<byte>("RUC");

                    b.Property<short>("STR");

                    b.Property<short>("Socket1");

                    b.Property<short>("Socket2");

                    b.Property<short>("Speed");

                    b.Property<string>("Title")
                        .HasColumnName("ItemSlotEquip_Title");

                    b.ToTable("ItemSlotEquip");

                    b.HasDiscriminator().HasValue("ItemSlotEquip");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlotPet", b =>
                {
                    b.HasBaseType("Edelstein.Database.Entities.Inventory.ItemSlot");

                    b.Property<short>("Attribute")
                        .HasColumnName("ItemSlotPet_Attribute");

                    b.Property<DateTime?>("DateDead");

                    b.Property<byte>("Level")
                        .HasColumnName("ItemSlotPet_Level");

                    b.Property<short>("PetAttribute");

                    b.Property<string>("PetName");

                    b.Property<short>("PetSkill");

                    b.Property<int>("RemainLife");

                    b.Property<byte>("Repleteness");

                    b.Property<short>("Tameness");

                    b.ToTable("ItemSlotPet");

                    b.HasDiscriminator().HasValue("ItemSlotPet");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.AccountData", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Account", "Account")
                        .WithMany("Data")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Character", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.AccountData", "Data")
                        .WithMany("Characters")
                        .HasForeignKey("DataID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.FunctionKey", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Character")
                        .WithMany("FunctionKeys")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemInventory", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Character")
                        .WithMany("Inventories")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlot", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory", "ItemInventory")
                        .WithMany("Items")
                        .HasForeignKey("ItemInventoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Macro", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Character")
                        .WithMany("Macros")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.QuickslotKey", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Character")
                        .WithMany("QuickslotKeys")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Shop.NPCShopItem", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Shop.NPCShop")
                        .WithMany("Items")
                        .HasForeignKey("NPCShopID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Edelstein.Database.Entities.SkillRecord", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Character")
                        .WithMany("SkillRecords")
                        .HasForeignKey("CharacterID");
                });
#pragma warning restore 612, 618
        }
    }
}
