// <auto-generated />
using System;
using Edelstein.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Edelstein.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180919133947_AddInventories")]
    partial class AddInventories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Edelstein.Database.Entities.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .HasMaxLength(128);

                    b.Property<string>("Username")
                        .HasMaxLength(13);

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("AP");

                    b.Property<int?>("AccountID");

                    b.Property<short>("DEX");

                    b.Property<int>("EXP");

                    b.Property<int>("Face");

                    b.Property<byte>("Gender");

                    b.Property<int>("HP");

                    b.Property<int>("Hair");

                    b.Property<short>("INT");

                    b.Property<int?>("InventoryCashID");

                    b.Property<int?>("InventoryConsumeID");

                    b.Property<int?>("InventoryEquippedCashID");

                    b.Property<int?>("InventoryEquippedID");

                    b.Property<int?>("InventoryEtcID");

                    b.Property<int?>("InventoryInstallID");

                    b.Property<short>("Job");

                    b.Property<short>("LUK");

                    b.Property<byte>("Level");

                    b.Property<int>("MP");

                    b.Property<int>("MaxHP");

                    b.Property<int>("MaxMP");

                    b.Property<int>("Money");

                    b.Property<string>("Name")
                        .HasMaxLength(13);

                    b.Property<short>("POP");

                    b.Property<short>("SP");

                    b.Property<short>("STR");

                    b.Property<byte>("Skin");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("InventoryCashID");

                    b.HasIndex("InventoryConsumeID");

                    b.HasIndex("InventoryEquippedCashID");

                    b.HasIndex("InventoryEquippedID");

                    b.HasIndex("InventoryEtcID");

                    b.HasIndex("InventoryInstallID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotBundle>", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("SlotMax");

                    b.HasKey("ID");

                    b.ToTable("ItemInventory<ItemSlotBundle>");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotEquip>", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("SlotMax");

                    b.HasKey("ID");

                    b.ToTable("ItemInventory<ItemSlotEquip>");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateExpire");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<short>("Slot");

                    b.Property<int>("TemplateID");

                    b.HasKey("ID");

                    b.ToTable("ItemSlot");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ItemSlot");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlotBundle", b =>
                {
                    b.HasBaseType("Edelstein.Database.Entities.Inventory.ItemSlot");

                    b.Property<short>("Attribute");

                    b.Property<int?>("ItemInventory<ItemSlotBundle>ID");

                    b.Property<short>("Number");

                    b.Property<string>("Title")
                        .HasMaxLength(13);

                    b.HasIndex("ItemInventory<ItemSlotBundle>ID");

                    b.HasDiscriminator().HasValue("ItemSlotBundle");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlotEquip", b =>
                {
                    b.HasBaseType("Edelstein.Database.Entities.Inventory.ItemSlot");

                    b.Property<short>("ACC");

                    b.Property<short>("Attribute")
                        .HasColumnName("ItemSlotEquip_Attribute");

                    b.Property<byte>("CHUC");

                    b.Property<byte>("CUC");

                    b.Property<short>("Craft");

                    b.Property<short>("DEX");

                    b.Property<int>("Durability");

                    b.Property<short>("EVA");

                    b.Property<int>("EXP");

                    b.Property<byte>("Grade");

                    b.Property<short>("INT");

                    b.Property<int>("IUC");

                    b.Property<int?>("ItemInventory<ItemSlotEquip>ID");

                    b.Property<short>("Jump");

                    b.Property<short>("LUK");

                    b.Property<byte>("Level");

                    b.Property<byte>("LevelUpType");

                    b.Property<short>("MAD");

                    b.Property<short>("MDD");

                    b.Property<short>("MaxHP");

                    b.Property<short>("MaxMP");

                    b.Property<short>("Option1");

                    b.Property<short>("Option2");

                    b.Property<short>("Option3");

                    b.Property<short>("PAD");

                    b.Property<short>("PDD");

                    b.Property<byte>("RUC");

                    b.Property<short>("STR");

                    b.Property<short>("Socket1");

                    b.Property<short>("Socket2");

                    b.Property<short>("Speed");

                    b.HasIndex("ItemInventory<ItemSlotEquip>ID");

                    b.HasDiscriminator().HasValue("ItemSlotEquip");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Character", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountID");

                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotBundle>", "InventoryCash")
                        .WithMany()
                        .HasForeignKey("InventoryCashID");

                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotBundle>", "InventoryConsume")
                        .WithMany()
                        .HasForeignKey("InventoryConsumeID");

                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotEquip>", "InventoryEquippedCash")
                        .WithMany()
                        .HasForeignKey("InventoryEquippedCashID");

                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotEquip>", "InventoryEquipped")
                        .WithMany()
                        .HasForeignKey("InventoryEquippedID");

                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotBundle>", "InventoryEtc")
                        .WithMany()
                        .HasForeignKey("InventoryEtcID");

                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotBundle>", "InventoryInstall")
                        .WithMany()
                        .HasForeignKey("InventoryInstallID");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlotBundle", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotBundle>")
                        .WithMany("Items")
                        .HasForeignKey("ItemInventory<ItemSlotBundle>ID");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Inventory.ItemSlotEquip", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Inventory.ItemInventory<Edelstein.Database.Entities.Inventory.ItemSlotEquip>")
                        .WithMany("Items")
                        .HasForeignKey("ItemInventory<ItemSlotEquip>ID");
                });
#pragma warning restore 612, 618
        }
    }
}
