// <auto-generated />
using System;
using Edelstein.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Edelstein.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Edelstein.Database.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .HasMaxLength(128);

                    b.Property<string>("Username")
                        .HasMaxLength(13);

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<short>("Ap");

                    b.Property<short>("Dex");

                    b.Property<int>("Exp");

                    b.Property<int>("Face");

                    b.Property<byte>("Gender");

                    b.Property<int>("Hair");

                    b.Property<int>("Hp");

                    b.Property<short>("Int");

                    b.Property<short>("Job");

                    b.Property<byte>("Level");

                    b.Property<short>("Luk");

                    b.Property<int>("MaxHp");

                    b.Property<int>("MaxMp");

                    b.Property<int>("Money");

                    b.Property<int>("Mp");

                    b.Property<string>("Name")
                        .HasMaxLength(13);

                    b.Property<short>("Pop");

                    b.Property<byte>("Skin");

                    b.Property<short>("Sp");

                    b.Property<short>("Str");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Edelstein.Database.Entities.Character", b =>
                {
                    b.HasOne("Edelstein.Database.Entities.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
